exports.words = [
  //SIMPLE
  {word: "House", category: "simple"},
  {word: "Chair", category: "simple"},
  {word: "Cup", category: "simple"},
  {word: "Ball", category: "simple"},
  {word: "Pen", category: "simple"},
  {word: "Swing", category: "simple"},
  {word: "Door", category: "simple"},
  {word: "Drum", category: "simple"},
  {word: "Skipping rope", category: "simple"},
  {word: "Sunglasses", category: "simple"},
  {word: "Star", category: "simple"},
  {word: "Moon", category: "simple"},
  {word: "Airplane", category: "simple"},
  {word: "Telephone", category: "simple"},
  {word: "Mason jar", category: "simple"},
  {word: "Room", category: "simple"},
  {word: "Turtle", category: "simple"},
  {word: "Doll", category: "simple"},
  {word: "Cycle", category: "simple"},
  {word: "Car", category: "simple"},
  {word: "Bottle", category: "simple"},
  {word: "Spoon", category: "simple"},
  {word: "Crayon", category: "simple"},
  {word: "Pencil", category: "simple"},
  {word: "Eraser", category: "simple"},
  {word: "Frame", category: "simple"},
  {word: "Santa Claus", category: "simple"},
  {word: "Ice cream", category: "simple"},

  //MEDIUM
  {word: "Basketball", category: "medium"},
  {word: "Skates", category: "medium"},
  {word: "Computer", category: "medium"},
  {word: "Scooter", category: "medium"},
  {word: "Bus", category: "medium"},
  {word: "Mobile phone", category: "medium"},
  {word: "Watch", category: "medium"},
  {word: "Flip-flops", category: "medium"},
  {word: "Cupcake", category: "medium"},
  {word: "Bicycle", category: "medium"},
  {word: "Helmet", category: "medium"},
  {word: "Glove", category: "medium"},
  {word: "Violin", category: "medium"},
  {word: "Guitar", category: "medium"},
  {word: "Ukulele", category: "medium"},
  {word: "Goldfish", category: "medium"},
  {word: "Pig", category: "medium"},
  {word: "Shoe", category: "medium"},
  {word: "Hat", category: "medium"},
  {word: "Kite", category: "medium"},
  {word: "Sock", category: "medium"},
  {word: "Christmas tree", category: "medium"},
  {word: "Doctor", category: "medium"},
  {word: "Painter", category: "medium"},
  {word: "Pokemon", category: "medium"},

  //HARD
  {word: "Rollerblades", category: "hard"},
  {word: "Kite surfing", category: "hard"},
  {word: "Ice skating", category: "hard"},
  {word: "Gymnastics", category: "hard"},
  {word: "Bike", category: "hard"},
  {word: "Bat", category: "hard"},
  {word: "Trampoline", category: "hard"},
  {word: "Torch", category: "hard"},
  {word: "Basket", category: "hard"},
  {word: "Spider web", category: "hard"},
  {word: "Shipwreck", category: "hard"},
  {word: "Journal", category: "hard"},
  {word: "Flag", category: "hard"},
  {word: "Invitation", category: "hard"},
  {word: "Team captain", category: "hard"},
  {word: "Dripping", category: "hard"},
  {word: "Cold", category: "hard"},
  {word: "Calendar", category: "hard"},
  {word: "Spitball", category: "hard"},
  {word: "Drinking fountain", category: "hard"},
  {word: "Communicate", category: "hard"},
  {word: "Girlfriend", category: "hard"},
  {word: "Chuck Norris", category: "hard"},
  {word: "Scuba diver", category: "hard"},
  {word: "Old woman", category: "hard"},
  {word: "Girl", category: "hard"},
  {word: "Boy", category: "hard"},
  {word: "Teenager", category: "hard"},
  {word: "Accountant", category: "hard"},
  {word: "Gasoline", category: "hard"},
  {word: "Gas station", category: "hard"},
  {word: "Airport", category: "hard"},
  {word: "Platform", category: "hard"},
  {word: "Mountain", category: "hard"},
  {word: "River", category: "hard"},
  {word: "Chewing gum", category: "hard"},
  {word: "Glue", category: "hard"},
  {word: "Geometry", category: "hard"},
  {word: "Lightning", category: "hard"},
  {word: "Prison", category: "hard"},
  {word: "Piano", category: "hard"},
  {word: "Newsletter", category: "hard"},
  {word: "Neutron", category: "hard"},

  //MOVIES
  {word: "Alien", category: "movie"},
  {word: "Flash", category: "movie"},
  {word: "Home Alone", category: "movie"},
  {word: "A Bug’s Life", category: "movie"},
  {word: "Terminator", category: "movie"},
  {word: "The Mask", category: "movie"},
  {word: "How to Train Your Dragon", category: "movie"},
  {word: "Guardians of the Galaxy", category: "movie"},
  {word: "Captain America", category: "movie"},
  {word: "Wonder Woman", category: "movie"},
  {word: "Aquaman", category: "movie"},
  {word: "Black Panther", category: "movie"},
  {word: "Smurfs", category: "movie"},
  {word: "Castaway", category: "movie"},
  {word: "Predator", category: "movie"},
  {word: "Star Trek", category: "movie"},
  {word: "King Kong", category: "movie"},
  {word: "Godzilla", category: "movie"},
  {word: "Star Wars", category: "movie"},
  {word: "Speed", category: "movie"},
  {word: "Night at the Museum", category: "movie"},
  {word: "Karate Kid", category: "movie"},
  {word: "Ninja Turtles", category: "movie"},
  {word: "Mrs. Doubtfire", category: "movie"},
  {word: "Jumanji", category: "movie"},
  {word: "Hercules", category: "movie"},
  {word: "He-Man", category: "movie"},
  {word: "Wizard of Oz", category: "movie"},
  {word: "Parent Trap", category: "movie"},
  {word: "Fatherhood", category: "movie"},
  {word: "Fast and Furious", category: "movie"},
  {word: "Twister", category: "movie"},
  {word: "Ant-man", category: "movie"},
  {word: "Black Beauty", category: "movie"},
  {word: "The Lion King", category: "movie"},
  {word: "Moana", category: "movie"},
  {word: "Finding Nemo", category: "movie"},
  {word: "Cinderella", category: "movie"},
  {word: "Finding Dory", category: "movie"},
  {word: "Mary Poppins", category: "movie"},
  {word: "Free Willy", category: "movie"},
  {word: "Anaconda", category: "movie"},
  {word: "Sound of Music", category: "movie"},
  {word: "Wall-E", category: "movie"},
  {word: "Jaws", category: "movie"},
  {word: "Spiderman", category: "movie"},
  {word: "Green Lantern", category: "movie"},
  {word: "Ironman", category: "movie"},
  {word: "Hulk", category: "movie"},
  {word: "Flubber", category: "movie"},
  {word: "A Pet’s Life", category: "movie"},
  {word: "101 Dalmatians", category: "movie"},
  {word: "Matilda", category: "movie"},
  {word: "Jungle Book", category: "movie"},
  {word: "Toy Story", category: "movie"},
  {word: "Red Riding Hood", category: "movie"},
  {word: "Snow White", category: "movie"},
  {word: "Tangled", category: "movie"},

  //FOOD
  {word: "Tomato", category: "food"},
  {word: "Spinach", category: "food"},
  {word: "Orange", category: "food"},
  {word: "Banana", category: "food"},
  {word: "Corn", category: "food"},
  {word: "Sugar cube", category: "food"},
  {word: "Salt", category: "food"},
  {word: "Grape", category: "food"},
  {word: "Mango", category: "food"},
  {word: "Watermelon", category: "food"},
  {word: "Lemon", category: "food"},
  {word: "Carrot", category: "food"},
  {word: "Pineapple", category: "food"},
  {word: "Kiwi", category: "food"},
  {word: "Spaghetti", category: "food"},
  {word: "Pasta", category: "food"},
  {word: "Pizza", category: "food"},
  {word: "Apple", category: "food"},
  {word: "Chips", category: "food"},
  {word: "Fries", category: "food"},
  {word: "Hash brown", category: "food"},
  {word: "Cereal", category: "food"},
  {word: "Doughnut", category: "food"},
  {word: "Potato", category: "food"},
  {word: "Cheesecake", category: "food"},
  {word: "BBQ", category: "food"},
  {word: "Turkey", category: "food"},
  {word: "Ketchup", category: "food"},
  {word: "Cheese", category: "food"},
  {word: "Cracker", category: "food"},
  {word: "Cookie", category: "food"},
  {word: "Cotton candy", category: "food"},
  {word: "Milkshake", category: "food"},
  {word: "Pop tart", category: "food"},
  {word: "Bacon", category: "food"},
  {word: "Sandwich", category: "food"},

  //HUMAN
  {word: "Stomach", category: "human"},
  {word: "Baby", category: "human"},
  {word: "Belly", category: "human"},
  {word: "Head", category: "human"},
  {word: "Mouth", category: "human"},
  {word: "Chin", category: "human"},
  {word: "Neck", category: "human"},
  {word: "Hands", category: "human"},
  {word: "Cheek", category: "human"},
  {word: "Ear", category: "human"},
  {word: "Smile", category: "human"},
  {word: "Cry", category: "human"},
  {word: "Sad", category: "human"},
  {word: "Angry", category: "human"},
  {word: "Confused", category: "human"},
  {word: "Happy", category: "human"},
  {word: "Nose", category: "human"},
  {word: "Eyes", category: "human"},
  {word: "Legs", category: "human"},
  {word: "Arm", category: "human"},
  {word: "Finger", category: "human"},
  {word: "Lips", category: "human"},
  {word: "Teeth", category: "human"},
  {word: "Heart", category: "human"},
  {word: "Surprise", category: "human"},
  {word: "Lung", category: "human"},

  //WORLD
  {word: "Spain", category: "world"},
  {word: "River", category: "world"},
  {word: "Sea", category: "world"},
  {word: "Continent", category: "world"},
  {word: "Country", category: "world"},
  {word: "Pacific Ocean", category: "world"},
  {word: "India", category: "world"},
  {word: "Afghanistan", category: "world"},
  {word: "New Zealand", category: "world"},
  {word: "Asia", category: "world"},
  {word: "Canada", category: "world"},
  {word: "Alaska", category: "world"},
  {word: "Australia", category: "world"},
  {word: "Antarctica", category: "world"},
  {word: "Russia", category: "world"},
  {word: "Mexico", category: "world"},
  {word: "China", category: "world"},
  {word: "Egypt", category: "world"},
  {word: "England", category: "world"},
  {word: "Scotland", category: "world"},
  {word: "Iceland", category: "world"},
  {word: "The White House", category: "world"},
  {word: "New York", category: "world"},
  {word: "Washington D.C.", category: "world"},
  {word: "United States", category: "world"},
  {word: "Thailand", category: "world"},

  //SPORTS
  {word: "Football", category: "sports"},
  {word: "Basketball", category: "sports"},
  {word: "Cricket", category: "sports"},
  {word: "Hockey", category: "sports"},
  {word: "Soccer", category: "sports"},
  {word: "Baseball", category: "sports"},
  {word: "Ice hockey", category: "sports"},
  {word: "Golf", category: "sports"},
  {word: "Table tennis", category: "sports"},
  {word: "Chess", category: "sports"},
  {word: "Surfing", category: "sports"},
  {word: "Horse riding", category: "sports"},
  {word: "Hopscotch", category: "sports"},
  {word: "Pole vault", category: "sports"},
  {word: "Gymnasium", category: "sports"},
  {word: "Homerun", category: "sports"},
  {word: "Pac-man", category: "sports"},
  {word: "Call of Duty", category: "sports"},
  {word: "Foosball", category: "sports"},
  {word: "Limbo", category: "sports"},
  {word: "Tennis", category: "sports"},

  //PLACE
  {word: "Mosque", category: "place"},
  {word: "Church", category: "place"},
  {word: "St. Petersburg", category: "place"},
  {word: "Machu Picchu", category: "place"},
  {word: "Christ the Redeemer", category: "place"},
  {word: "The Great Wall of China", category: "place"},
  {word: "Taj Mahal", category: "place"},
  {word: "The Grand Canyon", category: "place"},
  {word: "Island", category: "place"},
  {word: "Disneyland", category: "place"},
  {word: "Bathroom", category: "place"},
  {word: "Backyard", category: "place"},
  {word: "Bedroom", category: "place"},
  {word: "Kitchen", category: "place"},
  {word: "Playground", category: "place"},
  {word: "Bus stop", category: "place"},
  {word: "Library", category: "place"},
  {word: "School", category: "place"},
  {word: "University", category: "place"},
  {word: "Beverly Hills", category: "place"},
  {word: "Hollywood", category: "place"},
  {word: "Opera House", category: "place"},
  {word: "The Great Barrier Reef", category: "place"},
  {word: "Building", category: "place"},

  //VERB
  {word: "Blink", category: "verb"},
  {word: "Point", category: "verb"},
  {word: "Dance", category: "verb"},
  {word: "Skip", category: "verb"},
  {word: "Kick", category: "verb"},
  {word: "Jump", category: "verb"},
  {word: "Cycle", category: "verb"},
  {word: "Drink", category: "verb"},
  {word: "Trip", category: "verb"},
  {word: "Run", category: "verb"},
  {word: "Pinch", category: "verb"},
  {word: "Row", category: "verb"},
  {word: "Ski", category: "verb"},
  {word: "Snowboard", category: "verb"},
  {word: "Swim", category: "verb"},
  {word: "Coil", category: "verb"},
  {word: "Yell", category: "verb"},
  {word: "Pray", category: "verb"},
  {word: "Meditate", category: "verb"},
  {word: "Cook", category: "verb"},
  {word: "Rest", category: "verb"},
  {word: "Burp", category: "verb"},
  {word: "Listen", category: "verb"},
  {word: "Type", category: "verb"},
  {word: "Text", category: "verb"},
  {word: "Sing", category: "verb"},
  {word: "Wave", category: "verb"},

  //PEOPLE
  {word: "Donald Trump", category: "people"},
  {word: "Paul McCartney", category: "people"},
  {word: "Harry Potter", category: "people"},
  {word: "Voldemort", category: "people"},
  {word: "Batman", category: "people"},
  {word: "Justin Bieber", category: "people"},
  {word: "Selena Gomez", category: "people"},
  {word: "Superman", category: "people"},
  {word: "Spongebob", category: "people"},
  {word: "Barack Obama", category: "people"},
  {word: "Joe Biden", category: "people"},
  {word: "Teacher", category: "people"},
  {word: "Artist", category: "people"},
  {word: "Singer", category: "people"},
  {word: "Dancer", category: "people"},
  {word: "Athlete", category: "people"},
  {word: "Usain Bolt", category: "people"},
  {word: "Michael Jackson", category: "people"},
  {word: "Michael Phelps", category: "people"},
  {word: "Serena Williams", category: "people"},
  {word: "Novak Djokovic", category: "people"},
  {word: "Roger Federer", category: "people"},
  {word: "Rafael Nadal", category: "people"},
  {word: "Mona Lisa", category: "people"},
  {word: "Tom Hanks", category: "people"},
  {word: "Beyonce", category: "people"},
  {word: "Drummer", category: "people"},
  {word: "Guitarist", category: "people"},
  {word: "Chef", category: "people"},
  {word: "Waitress", category: "people"},
  {word: "Manager", category: "people"},
  {word: "Police officer", category: "people"},
  {word: "President", category: "people"},
  {word: "Hairstylist", category: "people"},
  {word: "Michael Jordan", category: "people"},
  {word: "Neil Armstrong", category: "people"},
  {word: "Scooby-Doo", category: "people"},
  {word: "Princess Leia", category: "people"},
  {word: "Sherlock Holmes", category: "people"},
  {word: "The Grinch", category: "people"},
  {word: "Elvis Presley", category: "people"},
  {word: "Waldo", category: "people"},
  {word: "Beethoven", category: "people"},
  {word: "Dr. Seuss", category: "people"},
  {word: "Albert Einstein", category: "people"},
  {word: "Steve Jobs", category: "people"}
]
